<?php

namespace App\Domain;

use Symfony\Component\VarDumper\Cloner\Data;
use Symfony\Component\VarDumper\Cloner\VarCloner;
use Symfony\Component\VarDumper\Dumper\CliDumper;

class MyCliDumper extends CliDumper
{
    protected VarCloner $cloner;
    public function __construct($output = null, ?string $charset = null, int $flags = 0)
    {
        parent::__construct($output, $charset, $flags);

        $this->cloner = new VarCloner();
        $this->cloner->addCasters([
            Rectangle::class => [RectangleCaster::class, 'castRectangle'],
            Plane::class => [PlaneCaster::class, 'castPlane']
        ]);
    }

    public function d($data): ?string
    {
        return parent::dump($this->cloner->cloneVar($data)); // TODO: Change the autogenerated stub
    }
}